# Generated by Django 6.0.1 on 2026-01-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendTraders', '0003_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='is_slider',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_type',
            field=models.CharField(choices=[('slider', 'Slider Only'), ('gallery', 'Gallery Only'), ('both', 'Both Slider & Gallery')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
